

# This file was *autogenerated* from the file beaver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
load('../mpc/share.sage')

class Source(object):
      def __init__(self, p):
            self.a = random.randint(_sage_const_0 ,p)
            self.b = random.randint(_sage_const_0 ,p)
            self.c = self.a*self.b
            self.left_a = random.randint(_sage_const_0 ,self.a)
            self.right_a = self.a - self.left_a
            self.left_b = random.randint(_sage_const_0 ,self.b)
            self.right_b = self.b - self.left_b
            self.left_c = random.randint(_sage_const_0 ,self.c)
            self.right_c = self.c - self.left_c

      def triplet(self, party_id):
            #triple = [self.left_a, self.left_b, self.left_c] if party_id==0 else [self.right_a, self.right_b, self.right_c]
            #return [AuthenticatedShare(share, self, party_id) for share in triple]
            return [AuthenticatedShare(share, self, party_id) for share in [_sage_const_1 ,_sage_const_1 ,_sage_const_2 ]]

