

# This file was *autogenerated* from the file test_curve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
load('curve.sage')
import random

pt = CurvePoint.random()
rnd = random.randint(_sage_const_0 , p)
s_ff = K(rnd)
s = int(s_ff)
assert s == rnd
s_inv_ff = _sage_const_1 /s_ff
s_inv = int(s_inv_ff)
assert K(s*s_inv) == K(_sage_const_1 )
assert (pt * int(K(s * s_inv))) == pt

