

# This file was *autogenerated* from the file test_inner_product.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)
load('proof.sage')
load('transcript.sage')

n = _sage_const_2 
Q = [CurvePoint.generator()*_sage_const_1 ]
H = [CurvePoint.generator()*_sage_const_1  for i in range(_sage_const_0 ,n)]
G = [CurvePoint.generator()*_sage_const_1  for i in range(_sage_const_0 ,n)]

a = [_sage_const_1 , _sage_const_2 ]
b = [_sage_const_2 , _sage_const_4 ]
c = [sum([a*b for a, b in zip(a, b)])]
y_inv = K(_sage_const_1 )
G_factors = [K(_sage_const_1 )]*n
H_factors = [y_inv**i for i in range(_sage_const_0 ,n)]

b_prime = [b*y for b, y in  zip(b, H_factors)]
a_prime = a.copy()

transcript = Transcript('bulletproof')

proof = Proof(transcript, Q, G_factors, H_factors, G, H, a, b)
ga_prime = CurvePoint.msm(G, a_prime)
print('ga_prime: {}'.format(ga_prime))
hb_prime = CurvePoint.msm(H, b_prime)
qc = CurvePoint.msm(Q, c)
P_res =  sum([ga_prime, hb_prime, qc])
print('P_res: {}'.format(P_res))
verifier = Transcript('bulletproof')
pp, p, _ = proof.verify(n, verifier, G_factors, H_factors, P_res, Q, G, H)

